FAT2-363 EPAO availability on course search
SkillsFundingAgency/das-find-epao-web pull request #15
Opened 2021-01-14 15:38 UTC by PeterDavidWilliams

2021-01-15 11:16 UTC, dashton82 requested changes

2021-01-15 11:16 UTC, dashton82 commented on src/SFA.DAS.FindEpao.Domain/Courses/EpaoListItem.cs
> +        public DateTime? EffectiveFrom { get; set; }
Should it be nullable?

2021-01-15 15:20 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindEpao.Web/Views/Courses/CourseEpaos.cshtml
> +<dt class="das-definition-list__title govuk-!-margin-bottom-1">Locations covered</dt><dd class="govuk-!-margin-bottom-1">@epao.Locations</dd>
fixed. Trolls have been scorned and have fled. For now.

2021-01-15 15:21 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindEpao.Web/Models/EpaoListItemViewModel.cs
> +        public DateTime? EffectiveFrom { get; set; }
Change made

2021-01-15 15:21 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindEpao.Domain/Courses/EpaoListItem.cs
> +        public DateTime? EffectiveFrom { get; set; }
Change made

2021-01-18 11:34 UTC, dashton82 approved these changes

2021-01-20 12:52 UTC, merged